### ISSUE TITLE
Is it possible to get a home page feed for the logged in user.

### ISSUE THREAD

**Issue by walking-octopus** [tombulled/innertube#23]

**Comment by tombulled** [comment]
Hi @walking-octopus, yes this is completely possible using this library. The process, however, will differ depending on your needs.

Just a few quick questions so that I can help you better:
1. Which service are you attempting to interact with? (YouTube, YouTube Music, YouTube Kids, YouTube Studio, YouTube TV)
2. Which platform are you attempting to mimic? (Web, iOS, Android, TV)

**Comment by walking-octopus** [comment]
For example, how would I fake a mobile YT app to get a YouTube user's feed?

**Comment by tombulled** [comment]
So for the YouTube app, there are the three main clients:
* `WEB` - Mimics a web browser (defaults to Firefox)
* `IOS` - Mimics an iOS device (defaults to an iPhone X)
* `ANDROID` - Mimics an Android device (defaults to a Nexus 5)

To get the user's home page, you can use the following browseId: `"FEwhat_to_watch"`

Therefore, a request for the user's home page would look like:
```python
import innertube

client = innertube.InnerTube("ANDROID")

data = client.browse("FEwhat_to_watch")
```

**Comment by walking-octopus** [comment]
Thanks!

**Comment by tombulled** [comment]
Authentication has not currently been implemented, however progress has been made on this front (see #11). Therefore, unfortunately for now, authentication will need to be implemented manually.

If you have any further questions/queries, let me know :slightly_smiling_face:
